providers:
  minikube:
    enabled: true
  aws:
    enabled: false

envId: ""

rbac:
  enabled: false

apocng:
  image:
    repository: k8sprayorg/
    name: site
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP

    nodePort: ""

    loadBalancerIP: ""
    loadBalancerSourceRanges: []

    annotations: {}

  resources: {}

  key:
  cert:

nginxBasicAuth:
  user: k8spray
  password: k8spray

  clientMaxBodySize: 100m
  proxyReadTimeout: 60s

  service:
    type: NodePort # or ClusterIP or LoadBalancer

    nodePort: ""

    loadBalancerIP: ""
    loadBalancerSourceRanges: []

    annotations: {}

  image:
    repository: quay.io/dtan4/
    name: nginx-basic-auth-proxy
    tag: latest
    pullPolicy: IfNotPresent
  resources: {}

spinnaker:
  application:
    name: lcm
    email: lcm@lcm

  minio:
    replicas: 1

  ui:
    service:
      type: ClusterIP

  providers:
    docker:
      accounts:
      - name: dockerhub
        address: https://index.docker.io
        repositories:
          - appropriate/curl
          - k8sprayorg/ansible
          - k8sprayorg/shellinabox

fluentd:
  enabled: false

dashboard:
  enabled: false
  service:
    type: LoadBalancer

    nodePort: ""

    loadBalancerIP: ""
    loadBalancerSourceRanges: []

wordpress:
  enabled: false
  wordpressUsername: k8spray
  wordpressPassword: k8spray
  serviceType: ClusterIP
  persistence:
    storageClass: gp2

  mariadb:
    mariadbDatabase: k8spray
    mariadbUser: k8spray
    persistence:
      storageClass: gp2
